package com.learntocode.springannotation.DI.client;

import org.springframework.context.support.ClassPathXmlApplicationContext;

import com.learntocode.springannotation.DI.services.CarService;

/**
 * This class demo the Method injection(injecting or using @Autowired with ANY custom method)
 * @author abhthora
 *
 */
public class MethodInjectionDemoApp {

	public static void main(String[] args) {
		
		// Load the config file.
		ClassPathXmlApplicationContext applicationContext = new ClassPathXmlApplicationContext("springconfig.xml");

		// Retrieve the bean instances(Here bean id is default, generated by
		// Spring based on class name).
		CarService car = applicationContext.getBean("audiCar", CarService.class);

		// Call the methods on bean(DI using custom method)
		car.getCar();
		System.out.println("Your Audi is " + car.getCarInsurance());

		// close the context
		applicationContext.close();

	}

}
