package com.learntocode.springannotation.DI.client;

import org.springframework.context.support.ClassPathXmlApplicationContext;

import com.learntocode.springannotation.DI.services.CarService;

/**
 * This class is use to demo DI with annotation (Constructor/Setter Injection)
 * @author abhthora
 *
 */
public class SpringAnnotationDIApp {
	
	public static void main(String[] args) {
		
		// Load the config file.
		ClassPathXmlApplicationContext applicationContext = new ClassPathXmlApplicationContext("springconfig.xml");

		// Retrieve the bean instances(Here bean id is default, generated by  Spring based on class name).
		CarService swiftCar = applicationContext.getBean("swiftDesireCar", CarService.class);
		
		// Retrieve the bean instances(Here we have used bean id which is our custom bean id of component).
		CarService hundaiCar = applicationContext.getBean("myCustomHundai", CarService.class);
		
		// Call the methods on bean(Constructor injection with annotation)
		swiftCar.getCar();
		System.out.println("your swift Desire is " +swiftCar.getCarInsurance());
		
		// Call the methods on bean(Setter injection with annotation)
		hundaiCar.getCar();
		System.out.println("your Hundai is " +hundaiCar.getCarInsurance());

		// close the context
		applicationContext.close();
	}
}
