package com.learntocode.springannotation.ioc.client;

import org.springframework.context.support.ClassPathXmlApplicationContext;

import com.learntocode.springannotation.ioc.services.CarService;

public class SpringAnnotationIOCApp {
	
	public static void main(String[] args) {
		
		// Load the config file.
		ClassPathXmlApplicationContext applicationContext = new ClassPathXmlApplicationContext("springconfig.xml");

		// Retrieve the bean instances(Here bean id is default, generated by  Spring based on class name).
		CarService swiftCar = applicationContext.getBean("swiftDesireCar", CarService.class);
		
		// Retrieve the bean instances(Here we have used bean id which is our custom bean id of component).
		CarService hundaiCar = applicationContext.getBean("myCustomHundai", CarService.class);
		
		// Call the methods on bean
		swiftCar.getCar();
		hundaiCar.getCar();

		// close the context
		applicationContext.close();
	}
}
